server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dsranking?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjdghk79M
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include=oauth: