server:
  address: localhost
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dsranking?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: wjdghk79M
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 06e4c0157f286d10d128
            client-secret: 680ad0dbbca51c13abaebaa951c2cc5180c2e275